# Generated by Django 6.1.1 on 2026-10-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('detail', models.TextField(verbose_name='Detalle')),
                ('image', models.ImageField(upload_to='news', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='F.de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='F. de Edición')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
