# Generated by Django 6.1.1 on 2026-10-03 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, help_text='Ej: Hongduck · Nemone', max_length=100, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='news',
            name='blurb',
            field=models.CharField(blank=True, help_text='Una o dos frases para las tarjetas. Si lo dejas vacío se usa el inicio del detalle.', max_length=160, verbose_name='Resumen corto'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, help_text='Ej: Romance · Slice of life', max_length=60, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='news',
            name='palette',
            field=models.CharField(choices=[('rosa', 'Rosa'), ('lila', 'Lila'), ('beige', 'Beige')], default='rosa', max_length=10, verbose_name='Color de la portada'),
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, help_text='De 0 a 5, con un decimal. Ej: 4.8', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional. Si la subes, reemplaza la portada de colores.', upload_to='news', verbose_name='Imagen'),
        ),
    ]
