# Generated by Django 6.1.1 on 2026-10-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_news_author_news_blurb_news_category_news_palette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
        migrations.AddField(
            model_name='news',
            name='reading_status',
            field=models.CharField(choices=[('leido', 'Leído'), ('leyendo', 'Leyendo'), ('pendiente', 'Pendiente')], default='leido', max_length=10, verbose_name='Estado de lectura'),
        ),
    ]
